services:
  taskman:
    build:
      context: taskman
    ports:
      - "4001:4001"
    depends_on:
      db:
        condition: service_healthy  
  db:
    image: postgres:latest
    restart: always
    user: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=postgres
    volumes: 
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: