services:
  taskman:
    build:
      context: taskman
    ports:
      - "4001:4001"
    depends_on:
      db:
        condition: service_healthy  
  authman:
    build:
      context: authman 
    ports:
      - "4002:4002"
    depends_on:
      db:
        condition: service_healthy  
  db:
    image: postgres:latest
    restart: always
    user: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=postgres
    volumes: 
      - postgres:/var/lib/postgresql/data
  caddy:
    image: caddy:2.8.4-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
volumes:
  caddy_data:
  caddy_config:
  postgres: