global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'caddy'
    static_configs:
      - targets: ['caddy:2019']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
